services:
  temporalite:
    container_name: temporalite
    build: https://github.com/temporalio/temporalite.git#main
    ports:
      - 7233:7233
      - 8233:8233
    stdin_open: true
    tty: true
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporalite
    environment:
      - TEMPORAL_CLI_ADDRESS=temporalite:7233
      - TEMPORAL_ADDRESS=temporalite:7233
    image: temporalio/admin-tools:1.17.5
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
            "CMD",
            "tctl",
            "--address",
            "temporalite:7233",
            "workflow",
            "list"
        ]
      interval: 1s
      timeout: 5s
      retries: 30
networks:
  default:
    external: true
    name: temporal-network

