{
 "title": "ReplaySDKDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completed Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_workflow_completed_total[1m])) by (namespace) or vector(0)",
     "legendFormat": "NS: {{namespace}}"
    }
   ]
  },
  {
   "title": "Failed Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(avg_over_time(temporal_workflow_failed_total[1m])) by(namespace)",
     "legendFormat": "NS: {{namespace}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workflow Task Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, activity_type, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}} ACT: {{activity_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Schedule to Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Schedule to Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Sticky Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_sticky_cache_size[1m])) by(namespace)",
     "legendFormat": "NS: {{namespace}}"
    }
   ]
  },
  {
   "title": "Active Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time(temporal_worker_task_slots_available{namespace=\"default\", worker_type!=\"LocalActivityWorker\"}[1m])) by (namespace, worker_type)",
     "legendFormat": "NS: {{namespace}} TQ: {{task_queue}} WT: {{worker_type}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_latency_seconds_max{namespace!=\"none\"}[1m])) by (namespace, task_queue)",
     "legendFormat": "NS: {{namespace}} TQ: {{task_queue}}"
    }
   ]
  },
  {
   "title": "Request Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_request_failure_total[1m])) by (namespace) or vector(0)",
     "legendFormat": "NS: {{namespace}} TQ: {{task_queue}}"
    }
   ]
  },
  {
   "title": "Long Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(temporal_long_request_latency_seconds_max{namespace!=\"none\"}[1m])) by (namespace, task_queue,operation)",
     "legendFormat": "NS: {{namespace}} TQ: {{task_queue}} OP: {{operation}}"
    }
   ]
  },
  {
   "title": "Long Request Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_long_request_failure_total[1m])) by (namespace) or vector(0)",
     "legendFormat": "NS: {{namespace}} "
    }
   ]
  }
 ]
}